version: '3.8'

services:
  # Spring Boot Backend
  backend:
    build: ../backend
    container_name: ecold_backend
    environment:
      # Firebase/Firestore
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID:-ecold-app-d3990}
      FIRESTORE_CREDENTIALS_PATH: ${FIRESTORE_CREDENTIALS_PATH:-classpath:firestore-key.json}

      # OAuth (from .env file)
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Application
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET:-ecold_development_secret_key}

    volumes:
      - upload_data:/app/uploads
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Angular Frontend
  frontend:
    build: ../frontend
    container_name: ecold_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  upload_data: