spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecold}
    username: ${DATABASE_USERNAME:ecold_user}
    password: ${DATABASE_PASSWORD:ecold_pass123}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  h2:
    console:
      enabled: false
      
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

logging:
  level:
    com.ecold: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE